/**
 * Auto-generated spell icon mapping from Foundry VTT dnd5e system packs.
 * Icons are served from /foundry-icons/* (data/foundry-icons/ on disk).
 * Re-generate by running the extraction script if spell packs are updated.
 */

const BASE = '/foundry-icons';

const NAME_MAP: Record<string, string> = {
  "polymorph": "icons/magic/control/energy-stream-link-large-teal.webp",
  "hunter's mark": "icons/magic/perception/eye-ringed-glow-angry-small-red.webp",
  "water breathing": "icons/magic/water/pseudopod-swirl-blue.webp",
  "dispel magic": "icons/skills/melee/strike-blade-knife-orange-blue.webp",
  "resilient sphere": "icons/magic/light/explosion-star-large-pink.webp",
  "conjure animals": "icons/magic/nature/wolf-paw-glow-large-orange.webp",
  "conjure elemental": "icons/magic/symbols/runes-star-pentagon-orange.webp",
  "invisibility": "icons/magic/air/fog-gas-smoke-dense-gray.webp",
  "glibness": "icons/magic/air/fog-gas-smoke-swirling-pink.webp",
  "knock": "icons/magic/symbols/runes-triangle-orange.webp",
  "hellish rebuke": "icons/magic/control/fear-fright-shadow-monster-red.webp",
  "gaseous form": "icons/magic/air/fog-gas-smoke-dense-green.webp",
  "sunbeam": "icons/magic/light/beams-rays-orange-purple-large.webp",
  "speak with plants": "icons/magic/nature/leaf-glow-teal.webp",
  "detect poison and disease": "icons/magic/air/air-burst-spiral-teal-green.webp",
  "heat metal": "icons/magic/light/explosion-star-large-orange.webp",
  "enthrall": "icons/magic/air/air-burst-spiral-pink.webp",
  "mass healing word": "icons/magic/life/heart-cross-strong-flame-green.webp",
  "power word stun": "icons/magic/control/debuff-chains-ropes-red.webp",
  "hold person": "icons/magic/control/debuff-chains-ropes-purple.webp",
  "calm emotions": "icons/magic/light/explosion-star-blue.webp",
  "identify": "icons/magic/light/explosion-star-small-teal-purple.webp",
  "wish": "icons/magic/symbols/runes-star-pentagon-orange-purple.webp",
  "magic missile": "icons/magic/fire/projectile-meteor-salvo-light-pink.webp",
  "planar binding": "icons/magic/symbols/runes-star-pentagon-orange.webp",
  "acid arrow": "icons/magic/acid/projectile-bolts-salvo-green.webp",
  "comprehend languages": "icons/magic/symbols/runes-triangle-orange-purple.webp",
  "contingency": "icons/magic/defensive/shield-barrier-flaming-pentagon-teal-purple.webp",
  "augury": "icons/magic/perception/eye-ringed-glow-angry-teal.webp",
  "mass suggestion": "icons/magic/air/air-burst-spiral-large-pink.webp",
  "burning hands": "icons/magic/air/fog-gas-smoke-dense-orange.webp",
  "silence": "icons/magic/symbols/runes-triangle-magenta.webp",
  "flame strike": "icons/magic/light/beam-rays-red-large.webp",
  "find steed": "icons/magic/nature/wolf-paw-glow-teal-blue.webp",
  "forbiddance": "icons/magic/symbols/runes-star-pentagon-orange.webp",
  "meld into stone": "icons/magic/earth/projectile-spiked-stone-boulder-blue.webp",
  "foresight": "icons/magic/perception/eye-ringed-glow-angry-large-teal.webp",
  "hypnotic pattern": "icons/magic/air/air-burst-spiral-pink.webp",
  "word of recall": "icons/magic/symbols/runes-star-pentagon-orange-purple.webp",
  "fabricate": "icons/magic/fire/explosion-fireball-medium-purple-orange.webp",
  "storm of vengeance": "icons/magic/light/projectile-beams-salvo-yellow.webp",
  "branding smite": "icons/magic/fire/dagger-rune-enchant-flame-orange.webp",
  "guiding bolt": "icons/magic/fire/projectile-fireball-smoke-large-blue.webp",
  "false life": "icons/magic/life/heart-cross-purple-orange.webp",
  "control water": "icons/magic/air/fog-gas-smoke-swirling-blue.webp",
  "alarm": "icons/magic/symbols/runes-triangle-orange-purple.webp",
  "scorching ray": "icons/magic/light/beam-rays-red.webp",
  "magic mouth": "icons/magic/air/wind-vortex-swirl-purple.webp",
  "illusory script": "icons/magic/air/fog-gas-smoke-purple.webp",
  "divine favor": "icons/magic/fire/dagger-rune-enchant-flame-blue-yellow.webp",
  "wind walk": "icons/magic/air/wind-swirl-gray-blue.webp",
  "alter self": "icons/magic/control/debuff-energy-hold-green.webp",
  "teleportation circle": "icons/magic/symbols/runes-star-pentagon-magenta.webp",
  "arcane lock": "icons/magic/symbols/runes-star-orange.webp",
  "bless": "icons/magic/control/buff-flight-wings-blue.webp",
  "secret chest": "icons/magic/perception/eye-ringed-glow-angry-teal.webp",
  "spare the dying": "icons/magic/life/heart-cross-blue.webp",
  "dominate person": "icons/magic/air/air-burst-spiral-large-pink.webp",
  "bane": "icons/magic/unholy/strike-beam-blood-red-purple.webp",
  "enhance ability": "icons/magic/control/buff-flight-wings-runes-purple.webp",
  "spike growth": "icons/magic/nature/vines-thorned-curled-glow-green.webp",
  "confusion": "icons/magic/air/wind-tornado-cyclone-purple-pink.webp",
  "regenerate": "icons/magic/life/heart-cross-strong-flame-green.webp",
  "disguise self": "icons/magic/control/debuff-energy-hold-teal-blue.webp",
  "dimension door": "icons/magic/air/air-burst-spiral-large-pink.webp",
  "raise dead": "icons/magic/life/heart-cross-strong-purple-orange.webp",
  "wall of thorns": "icons/magic/light/beam-rays-green-large.webp",
  "animate objects": "icons/magic/earth/projectile-stone-boulder-purple.webp",
  "flame blade": "icons/magic/fire/dagger-rune-enchant-flame-orange.webp",
  "delayed blast fireball": "icons/magic/fire/projectile-fireball-smoke-strong-orange.webp",
  "longstrider": "icons/magic/air/wind-stream-blue-gray.webp",
  "symbol": "icons/magic/symbols/runes-star-pentagon-blue.webp",
  "daylight": "icons/magic/light/beam-rays-yellow.webp",
  "hideous laughter": "icons/magic/fire/explosion-fireball-medium-purple-pink.webp",
  "create food and water": "icons/magic/nature/leaf-glow-teal.webp",
  "phantasmal killer": "icons/magic/control/fear-fright-monster-grin-purple-blue.webp",
  "light": "icons/magic/light/explosion-star-small-blue-yellow.webp",
  "silent image": "icons/magic/air/air-burst-spiral-teal-green.webp",
  "dancing lights": "icons/magic/fire/projectile-meteor-salvo-strong-blue.webp",
  "mage armor": "icons/magic/defensive/shield-barrier-glowing-triangle-blue.webp",
  "contagion": "icons/magic/unholy/strike-beam-blood-large-red-purple.webp",
  "zone of truth": "icons/magic/symbols/runes-star-magenta.webp",
  "black tentacles": "icons/magic/nature/vines-thorned-curled-glow-teal-purple.webp",
  "see invisibility": "icons/magic/perception/eye-ringed-glow-angry-teal.webp",
  "tree stride": "icons/magic/nature/leaf-glow-maple-orange-purple.webp",
  "create undead": "icons/magic/control/fear-fright-monster-grin-red-orange.webp",
  "fire bolt": "icons/magic/fire/projectile-fireball-smoke-orange.webp",
  "reverse gravity": "icons/magic/control/debuff-energy-hold-yellow.webp",
  "counterspell": "icons/skills/melee/strike-blade-hooked-orange-blue.webp",
  "antimagic field": "icons/magic/control/debuff-chains-ropes-net-purple-blue.webp",
  "lesser restoration": "icons/magic/life/heart-cross-blue.webp",
  "gust of wind": "icons/magic/air/wind-swirl-gray-blue.webp",
  "flaming sphere": "icons/magic/light/explosion-star-large-orange.webp",
  "antipathy/sympathy": "icons/magic/control/fear-fright-monster-grin-green.webp",
  "blink": "icons/magic/control/debuff-energy-hold-pink.webp",
  "sending": "icons/magic/air/wind-vortex-swirl-purple.webp",
  "disintegrate": "icons/magic/unholy/strike-beam-blood-large-red-purple.webp",
  "finger of death": "icons/magic/unholy/strike-beam-blood-large-red-purple.webp",
  "telekinesis": "icons/magic/control/debuff-energy-hold-levitate-yellow.webp",
  "speak with dead": "icons/magic/control/fear-fright-shadow-monster-green.webp",
  "fog cloud": "icons/magic/air/fog-gas-smoke-dense-gray.webp",
  "arcane eye": "icons/magic/perception/eye-ringed-glow-angry-teal.webp",
  "locate animals or plants": "icons/magic/nature/leaf-glow-triple-orange-purple.webp",
  "lightning bolt": "icons/magic/lightning/bolt-forked-large-blue.webp",
  "fire storm": "icons/magic/fire/projectile-meteor-salvo-heavy-red.webp",
  "plane shift": "icons/magic/symbols/runes-star-pentagon-orange-purple.webp",
  "find familiar": "icons/magic/nature/wolf-paw-glow-purple-teal.webp",
  "acid splash": "icons/magic/fire/projectile-fireball-smoke-green.webp",
  "barkskin": "icons/magic/defensive/shield-barrier-flaming-diamond-orange.webp",
  "geas": "icons/magic/air/air-burst-spiral-large-yellow.webp",
  "warding bond": "icons/magic/defensive/shield-barrier-flaming-diamond-blue-yellow.webp",
  "time stop": "icons/magic/time/clock-stopwatch-white-blue.webp",
  "spiritual weapon": "icons/magic/fire/dagger-rune-enchant-flame-purple.webp",
  "spider climb": "icons/magic/control/debuff-chains-blue.webp",
  "circle of death": "icons/magic/air/air-burst-spiral-large-teal-green.webp",
  "conjure minor elementals": "icons/magic/symbols/runes-star-orange.webp",
  "sleep": "icons/magic/light/explosion-star-small-pink.webp",
  "purify food and drink": "icons/magic/light/explosion-star-small-teal.webp",
  "find traps": "icons/magic/light/explosion-star-blue-small.webp",
  "teleport": "icons/magic/symbols/runes-star-pentagon-magenta.webp",
  "arcane sword": "icons/skills/melee/strike-blade-hooked-orange-blue.webp",
  "color spray": "icons/magic/air/fog-gas-smoke-dense-pink.webp",
  "cloudkill": "icons/magic/air/fog-gas-smoke-swirling-green.webp",
  "revivify": "icons/magic/life/heart-cross-strong-blue.webp",
  "dominate beast": "icons/magic/air/air-burst-spiral-large-teal-green.webp",
  "protection from poison": "icons/magic/defensive/shield-barrier-glowing-triangle-green.webp",
  "mislead": "icons/magic/control/debuff-energy-hold-levitate-blue-yellow.webp",
  "awaken": "icons/magic/nature/leaf-glow-maple-orange-purple.webp",
  "freezing sphere": "icons/magic/light/explosion-star-blue-large.webp",
  "continual flame": "icons/magic/fire/explosion-fireball-medium-orange.webp",
  "prayer of healing": "icons/magic/life/heart-cross-strong-green.webp",
  "levitate": "icons/magic/control/debuff-energy-hold-levitate-pink.webp",
  "thaumaturgy": "icons/magic/fire/explosion-fireball-small-purple-orange.webp",
  "detect evil and good": "icons/magic/air/air-burst-spiral-blue-gray.webp",
  "shapechange": "icons/magic/nature/wolf-paw-glow-large-orange.webp",
  "private sanctum": "icons/magic/defensive/shield-barrier-flaming-diamond-orange.webp",
  "tiny hut": "icons/magic/symbols/runes-star-blue.webp",
  "wall of stone": "icons/magic/light/beam-rays-orange-large.webp",
  "ray of enfeeblement": "icons/magic/light/beam-rays-teal.webp",
  "insect plague": "icons/magic/nature/leaf-glow-maple-teal.webp",
  "aid": "icons/magic/life/heart-cross-blue.webp",
  "compulsion": "icons/magic/fire/explosion-fireball-large-purple-pink.webp",
  "guidance": "icons/magic/control/buff-flight-wings-blue.webp",
  "etherealness": "icons/magic/air/fog-gas-smoke-swirling-white.webp",
  "mass cure wounds": "icons/magic/life/heart-cross-strong-green.webp",
  "true polymorph": "icons/magic/control/debuff-energy-snare-purple-pink.webp",
  "chain lightning": "icons/magic/lightning/bolt-forked-blue.webp",
  "goodberry": "icons/magic/nature/leaf-glow-green.webp",
  "stone shape": "icons/magic/earth/projectile-spiked-stone-boulder-blue.webp",
  "stoneskin": "icons/magic/defensive/shield-barrier-flaming-diamond-orange.webp",
  "cone of cold": "icons/magic/water/projectiles-ice-faceted-shard-salvo-blue.webp",
  "arcanist's magic aura": "icons/magic/symbols/runes-star-magenta.webp",
  "darkness": "icons/magic/perception/eye-ringed-glow-angry-red.webp",
  "faithful hound": "icons/magic/nature/wolf-paw-glow-large-purple-teal.webp",
  "hallow": "icons/magic/light/explosion-star-large-teal.webp",
  "druidcraft": "icons/magic/nature/vines-thorned-glow-teal.webp",
  "magic weapon": "icons/magic/fire/dagger-rune-enchant-flame-blue.webp",
  "instant summons": "icons/magic/symbols/runes-star-blue.webp",
  "locate object": "icons/magic/earth/projectile-stone-boulder-purple.webp",
  "haste": "icons/magic/control/buff-flight-wings-runes-purple.webp",
  "divine word": "icons/magic/light/explosion-star-large-orange-purple.webp",
  "astral projection": "icons/magic/control/debuff-energy-hold-levitate-teal-blue.webp",
  "irresistible dance": "icons/magic/control/energy-stream-link-large-blue.webp",
  "guardian of faith": "icons/magic/control/buff-flight-wings-runes-blue-white.webp",
  "dispel evil and good": "icons/magic/air/air-burst-spiral-large-blue.webp",
  "stinking cloud": "icons/magic/air/fog-gas-smoke-dense-green.webp",
  "blur": "icons/magic/air/air-burst-spiral-blue-gray.webp",
  "web": "icons/magic/control/debuff-chains-ropes-net-white.webp",
  "vampiric touch": "icons/magic/unholy/strike-beam-blood-red-gray.webp",
  "mage hand": "icons/magic/water/water-hand.webp",
  "death ward": "icons/magic/control/fear-fright-monster-purple-blue.webp",
  "shillelagh": "icons/magic/fire/dagger-rune-enchant-teal.webp",
  "legend lore": "icons/magic/symbols/runes-star-orange-purple.webp",
  "ice storm": "icons/magic/water/projectiles-ice-faceted-shard-salvo-blue.webp",
  "thunderwave": "icons/magic/lightning/bolt-forked-teal.webp",
  "enlarge/reduce": "icons/magic/control/energy-stream-link-large-blue.webp",
  "weird": "icons/magic/control/fear-fright-monster-grin-green.webp",
  "globe of invulnerability": "icons/magic/defensive/shield-barrier-flaming-pentagon-blue.webp",
  "greater restoration": "icons/magic/life/heart-cross-strong-flame-blue.webp",
  "wall of fire": "icons/magic/air/fog-gas-smoke-swirling-orange.webp",
  "mirror image": "icons/magic/control/debuff-energy-hold-levitate-pink.webp",
  "animal messenger": "icons/magic/nature/wolf-paw-glow-small-teal-blue.webp",
  "conjure celestial": "icons/magic/symbols/runes-star-pentagon-orange-purple.webp",
  "fear": "icons/magic/control/fear-fright-monster-purple-blue.webp",
  "remove curse": "icons/magic/life/heart-cross-strong-purple-orange.webp",
  "gate": "icons/magic/symbols/runes-star-pentagon-orange.webp",
  "divination": "icons/magic/light/beam-rays-blue.webp",
  "shocking grasp": "icons/magic/lightning/bolt-forked-blue.webp",
  "true seeing": "icons/magic/perception/eye-ringed-glow-angry-large-teal.webp",
  "mass heal": "icons/magic/life/heart-cross-strong-flame-green.webp",
  "forcecage": "icons/magic/control/debuff-chains-ropes-net-purple-blue.webp",
  "water walk": "icons/creatures/slimes/slime-movement-swirling-blue.webp",
  "plant growth": "icons/magic/nature/leaf-glow-triple-green.webp",
  "eldritch blast": "icons/magic/fire/projectile-fireball-smoke-teal.webp",
  "control weather": "icons/magic/air/wind-tornado-cyclone-white.webp",
  "eyebite": "icons/magic/perception/eye-ringed-glow-angry-large-red.webp",
  "beacon of hope": "icons/magic/light/explosion-star-large-blue-yellow.webp",
  "imprisonment": "icons/magic/control/debuff-chains-ropes-net-red-orange.webp",
  "jump": "icons/magic/control/debuff-energy-hold-blue-yellow.webp",
  "arcane hand": "icons/magic/fire/projectile-fireball-smoke-strong-teal.webp",
  "create or destroy water": "icons/magic/air/wind-swirl-purple-blue.webp",
  "speak with animals": "icons/magic/nature/wolf-paw-glow-small-teal-blue.webp",
  "nondetection": "icons/magic/perception/eye-ringed-glow-angry-red.webp",
  "rope trick": "icons/skills/melee/strike-blade-scimitar-gray-red.webp",
  "command": "icons/magic/fire/explosion-fireball-small-purple.webp",
  "fire shield": "icons/magic/defensive/shield-barrier-flaming-pentagon-red.webp",
  "programmed illusion": "icons/magic/control/debuff-chains-ropes-net-purple-blue.webp",
  "moonbeam": "icons/magic/light/beam-rays-blue-large.webp",
  "mind blank": "icons/magic/air/air-burst-spiral-large-blue.webp",
  "floating disk": "icons/magic/symbols/runes-triangle-blue.webp",
  "find the path": "icons/magic/light/explosion-star-teal.webp",
  "unseen servant": "icons/magic/control/debuff-energy-hold-blue-yellow.webp",
  "vicious mockery": "icons/skills/toxins/cup-goblet-poisoned-spilled.webp",
  "clairvoyance": "icons/magic/perception/eye-ringed-glow-angry-teal.webp",
  "maze": "icons/magic/control/debuff-chains-ropes-net-purple-blue.webp",
  "ray of frost": "icons/magic/light/beam-rays-blue-small.webp",
  "giant insect": "icons/magic/nature/leaf-glow-triple-orange.webp",
  "commune": "icons/magic/control/debuff-energy-hold-levitate-blue-yellow.webp",
  "passwall": "icons/magic/symbols/runes-star-pentagon-blue.webp",
  "conjure woodland beings": "icons/magic/nature/leaf-glow-maple-orange.webp",
  "blade barrier": "icons/magic/light/projectile-beams-salvo-white.webp",
  "contact other plane": "icons/magic/control/debuff-energy-hold-levitate-teal-blue.webp",
  "freedom of movement": "icons/skills/melee/strike-blade-knife-white-red.webp",
  "sleet storm": "icons/magic/water/projectile-beams-salvo-blue.webp",
  "resistance": "icons/magic/defensive/shield-barrier-glowing-triangle-orange.webp",
  "power word kill": "icons/magic/unholy/strike-beam-blood-large-red-teal.webp",
  "commune with nature": "icons/magic/nature/leaf-glow-triple-green.webp",
  "produce flame": "icons/magic/fire/explosion-fireball-medium-orange.webp",
  "dominate monster": "icons/magic/air/air-burst-spiral-large-pink.webp",
  "prismatic spray": "icons/magic/light/projectile-beams-salvo-yellow.webp",
  "project image": "icons/magic/control/energy-stream-link-spiral-teal.webp",
  "charm person": "icons/magic/fire/explosion-fireball-medium-purple-pink.webp",
  "call lightning": "icons/magic/lightning/bolt-forked-large-blue-yellow.webp",
  "magic jar": "icons/magic/defensive/shield-barrier-flaming-pentagon-teal-purple.webp",
  "grease": "icons/magic/air/fog-gas-smoke-orange.webp",
  "wind wall": "icons/magic/air/fog-gas-smoke-swirling-white.webp",
  "mirage arcane": "icons/magic/air/fog-gas-smoke-swirling-blue.webp",
  "scrying": "icons/magic/perception/eye-ringed-glow-angry-large-teal.webp",
  "planar ally": "icons/magic/symbols/runes-star-pentagon-magenta.webp",
  "wall of ice": "icons/magic/light/beam-rays-blue-large.webp",
  "poison spray": "icons/magic/fire/projectile-fireball-smoke-large-green.webp",
  "entangle": "icons/magic/nature/vines-thorned-curled-glow-green.webp",
  "locate creature": "icons/magic/nature/leaf-glow-maple-orange-purple.webp",
  "heroism": "icons/magic/life/heart-cross-strong-blue.webp",
  "detect magic": "icons/magic/light/explosion-star-blue.webp",
  "tongues": "icons/commodities/currency/coin-engraved-sun-smile-copper.webp",
  "sanctuary": "icons/magic/defensive/shield-barrier-flaming-diamond-blue-yellow.webp",
  "clone": "icons/magic/control/debuff-energy-hold-yellow.webp",
  "animal friendship": "icons/magic/nature/wolf-paw-glow-teal-blue.webp",
  "darkvision": "icons/magic/perception/eye-ringed-glow-angry-small-red.webp",
  "feeblemind": "icons/magic/light/explosion-star-large-teal-purple.webp",
  "sunburst": "icons/magic/fire/explosion-fireball-large-purple-orange.webp",
  "message": "icons/commodities/currency/coin-engraved-sun-smile-copper.webp",
  "protection from energy": "icons/magic/defensive/shield-barrier-flaming-diamond-teal.webp",
  "holy aura": "icons/magic/control/buff-flight-wings-runes-blue-white.webp",
  "shield of faith": "icons/magic/defensive/shield-barrier-flaming-diamond-blue-yellow.webp",
  "simulacrum": "icons/magic/control/energy-stream-link-spiral-orange.webp",
  "resurrection": "icons/magic/life/heart-cross-strong-flame-blue.webp",
  "prismatic wall": "icons/magic/light/beams-rays-orange-purple.webp",
  "dream": "icons/magic/air/fog-gas-smoke-swirling-pink.webp",
  "mending": "icons/magic/air/wind-stream-purple-blue.webp",
  "flesh to stone": "icons/magic/control/energy-stream-link-large-blue.webp",
  "inflict wounds": "icons/magic/unholy/strike-beam-blood-red-teal.webp",
  "hold monster": "icons/magic/control/debuff-chains-ropes-red.webp",
  "creation": "icons/magic/nature/vines-thorned-entwined-glow-teal-purple.webp",
  "meteor swarm": "icons/magic/fire/projectile-meteor-salvo-heavy-red.webp",
  "true strike": "icons/magic/fire/dagger-rune-enchant-blue-gray.webp",
  "seeming": "icons/magic/air/air-burst-spiral-pink.webp",
  "heroes' feast": "icons/magic/life/heart-cross-strong-flame-purple-orange.webp",
  "gentle repose": "icons/magic/light/explosion-star-blue.webp",
  "sacred flame": "icons/magic/light/beam-rays-orange.webp",
  "faerie fire": "icons/magic/fire/projectile-meteor-salvo-strong-teal.webp",
  "major image": "icons/magic/control/debuff-energy-hold-levitate-pink.webp",
  "healing word": "icons/magic/life/heart-cross-green.webp",
  "wall of force": "icons/magic/light/beam-rays-magenta-large.webp",
  "minor illusion": "icons/magic/control/hypnosis-mesmerism-eye.webp",
  "animal shapes": "icons/magic/nature/wolf-paw-glow-large-teal-blue.webp",
  "animate dead": "icons/magic/control/fear-fright-monster-red.webp",
  "glyph of warding": "icons/magic/symbols/runes-star-orange-purple.webp",
  "bestow curse": "icons/magic/control/buff-flight-wings-runes-red.webp",
  "pass without trace": "icons/magic/air/fog-gas-smoke-brown.webp",
  "incendiary cloud": "icons/magic/air/fog-gas-smoke-swirling-orange.webp",
  "magnificent mansion": "icons/magic/symbols/runes-star-pentagon-orange-purple.webp",
  "detect thoughts": "icons/magic/light/explosion-star-teal-purple.webp",
  "feather fall": "icons/magic/air/wind-swirl-pink-purple.webp",
  "banishment": "icons/magic/control/energy-stream-link-spiral-teal.webp",
  "blight": "icons/magic/unholy/strike-beam-blood-large-red-green.webp",
  "true resurrection": "icons/magic/life/heart-cross-strong-flame-blue.webp",
  "heal": "icons/magic/life/heart-cross-strong-flame-green.webp",
  "modify memory": "icons/magic/air/air-burst-spiral-large-teal-green.webp",
  "transport via plants": "icons/magic/nature/leaf-glow-maple-teal.webp",
  "hallucinatory terrain": "icons/magic/air/air-burst-spiral-teal-green.webp",
  "greater invisibility": "icons/magic/air/fog-gas-smoke-swirling-gray.webp",
  "harm": "icons/magic/unholy/strike-beam-blood-large-red-purple.webp",
  "telepathic bond": "icons/magic/control/energy-stream-link-blue.webp",
  "spirit guardians": "icons/magic/light/projectile-bolts-salvo-white.webp",
  "cure wounds": "icons/magic/life/heart-cross-green.webp",
  "prestidigitation": "icons/magic/fire/explosion-fireball-small-purple-orange.webp",
  "chill touch": "icons/magic/water/projectile-ice-faceted-blue.webp",
  "shatter": "icons/magic/fire/explosion-fireball-medium-blue.webp",
  "antilife shell": "icons/magic/defensive/shield-barrier-flaming-diamond-teal.webp",
  "phantom steed": "icons/magic/nature/wolf-paw-glow-teal-blue.webp",
  "misty step": "icons/magic/control/debuff-energy-snare-brown.webp",
  "sequester": "icons/magic/control/debuff-chains-ropes-purple.webp",
  "earthquake": "icons/magic/earth/projectile-spiked-stone-boulder-orange.webp",
  "demiplane": "icons/magic/symbols/runes-star-pentagon-blue.webp",
  "protection from evil and good": "icons/magic/defensive/shield-barrier-flaming-diamond-blue-yellow.webp",
  "magic circle": "icons/magic/symbols/runes-star-pentagon-blue.webp",
  "move earth": "icons/magic/earth/projectile-spiked-stone-boulder-orange.webp",
  "conjure fey": "icons/magic/symbols/runes-star-pentagon-blue.webp",
  "fly": "icons/magic/control/energy-stream-link-white.webp",
  "slow": "icons/magic/air/fog-gas-smoke-dense-pink.webp",
  "guards and wards": "icons/magic/symbols/runes-star-pentagon-magenta.webp",
  "shield": "icons/magic/defensive/shield-barrier-glowing-triangle-magenta.webp",
  "suggestion": "icons/magic/air/air-burst-spiral-pink.webp",
  "reincarnate": "icons/magic/life/heart-cross-strong-flame-blue.webp",
  "expeditious retreat": "icons/magic/air/wind-stream-blue-gray.webp",
  "fireball": "icons/magic/fire/projectile-fireball-smoke-large-orange.webp",
  "blindness/deafness": "icons/magic/perception/eye-ringed-glow-angry-red.webp",
  "symbol (stunning)": "icons/magic/symbols/runes-star-pentagon-blue.webp",
  "symbol (pain)": "icons/magic/symbols/runes-star-pentagon-blue.webp",
  "symbol (sleep)": "icons/magic/symbols/runes-star-pentagon-blue.webp",
  "symbol (fear)": "icons/magic/symbols/runes-star-pentagon-blue.webp",
  "antipathy": "icons/magic/control/fear-fright-monster-grin-green.webp",
  "magic weapon, +3": "icons/magic/fire/dagger-rune-enchant-flame-blue.webp",
  "magic weapon, +2": "icons/magic/fire/dagger-rune-enchant-flame-blue.webp",
  "magic weapon, +1": "icons/magic/fire/dagger-rune-enchant-flame-blue.webp",
  "divine word (30 hp or fewer)": "icons/magic/light/explosion-star-large-orange-purple.webp",
  "divine word (40 hp or fewer)": "icons/magic/light/explosion-star-large-orange-purple.webp",
  "divine word (50 hp or fewer)": "icons/magic/light/explosion-star-large-orange-purple.webp",
  "eyebite (alseep)": "icons/magic/perception/eye-ringed-glow-angry-large-red.webp",
  "eyebite (panicked)": "icons/magic/perception/eye-ringed-glow-angry-large-red.webp",
  "hopeful": "icons/magic/light/explosion-star-large-blue-yellow.webp",
  "chill shield": "icons/magic/defensive/shield-barrier-flaming-pentagon-blue.webp",
  "warm shield": "icons/magic/defensive/shield-barrier-flaming-pentagon-red.webp",
  "prismatic spray (indigo)": "icons/magic/light/projectile-beams-salvo-yellow.webp",
  "prismatic spray (violet)": "icons/magic/light/projectile-beams-salvo-yellow.webp",
  "cursed resilience": "icons/skills/wounds/bone-broken-marrow-red.webp",
  "cursed actions": "icons/magic/control/debuff-chains-shackles-movement-blue.webp",
  "cursed intelligence": "systems/dnd5e/icons/svg/abilities/intelligence.svg",
  "cursed charisma": "systems/dnd5e/icons/svg/abilities/charisma.svg",
  "cursed dexterity": "systems/dnd5e/icons/svg/abilities/dexterity.svg",
  "cursed attacks": "icons/skills/melee/sword-damaged-broken-purple.webp",
  "cursed constitution": "systems/dnd5e/icons/svg/abilities/constitution.svg",
  "cursed wisdom": "systems/dnd5e/icons/svg/abilities/wisdom.svg",
  "cursed strength": "systems/dnd5e/icons/svg/abilities/strength.svg",
  "blindness": "icons/magic/perception/eye-ringed-glow-angry-red.webp",
  "deafness": "icons/magic/perception/eye-ringed-glow-angry-red.webp",
  "phantasmal force": "icons/creatures/magical/spirit-undead-winged-ghost.webp",
  "arcane vigor": "icons/magic/life/cross-embers-glow-yellow-purple.webp",
  "aura of life": "icons/magic/holy/meditation-chi-focus-blue.webp",
  "befuddlement": "icons/skills/trades/academics-investigation-puzzles.webp",
  "charm monster": "icons/creatures/magical/humanoid-silhouette-glowing-pink.webp",
  "chromatic orb": "icons/magic/light/explosion-star-small-teal-purple.webp",
  "dissonant whispers": "icons/magic/sonic/projectile-sound-rings-wave.webp",
  "divine smite": "icons/skills/melee/strike-flail-destructive-yellow.webp",
  "dragon's breath": "icons/creatures/abilities/dragon-fire-breath-orange.webp",
  "elementalism": "icons/magic/nature/leaf-hand-green.webp",
  "ensnaring strike": "icons/magic/nature/root-vines-grow-brown.webp",
  "hex": "icons/magic/symbols/star-yellow.webp",
  "ice knife": "icons/magic/water/projectile-ice-shard.webp",
  "mind spike": "icons/magic/unholy/beam-ringed-impact-purple.webp",
  "power word heal": "icons/magic/life/heart-red-blue.webp",
  "ray of sickness": "icons/magic/unholy/beam-impact-green.webp",
  "searing smite": "icons/weapons/hammers/hammer-double-glowing-yellow.webp",
  "shining smite": "icons/skills/melee/strike-sword-dagger-runes-yellow.webp",
  "sorcerous burst": "icons/magic/lightning/bolt-strike-embers-teal.webp",
  "starry wisp": "icons/magic/light/orb-hand-green.webp",
  "summon dragon": "icons/creatures/abilities/dragon-breath-purple.webp",
  "tsunami": "icons/magic/water/wave-water-blue.webp",
  "vitriolic sphere": "icons/magic/acid/orb-bubble-smoke-drip.webp",
  "magical berries": "icons/consumables/fruit/lingonberry-cluster-red.webp",
  "protected": "icons/magic/holy/yin-yang-balance-symbol.webp",
  "seeing illusions": "icons/magic/control/hypnosis-mesmerism-eye.webp",
  "lightning protection": "icons/magic/lightning/bolt-strike-blue-white.webp",
  "fire protection": "icons/magic/fire/flame-burning-skull-orange.webp",
  "thunder protection": "icons/magic/sonic/explosion-shock-wave-teal.webp",
  "acid protection": "icons/magic/acid/dissolve-drip-droplet-smoke.webp",
  "cold protection": "icons/magic/water/snowflake-ice-snow-white.webp",
  "warded": "icons/skills/social/peace-luck-insult.webp",
  "level 4: +15 max hp": "icons/magic/life/cross-flared-green.webp",
  "level 8: +35 max hp": "icons/magic/life/cross-flared-green.webp",
  "level 5: +20 max hp": "icons/magic/life/cross-flared-green.webp",
  "level 2: +5 max hp": "icons/magic/life/cross-flared-green.webp",
  "level 9: +40 max hp": "icons/magic/life/cross-flared-green.webp",
  "level 3: +10 max hp": "icons/magic/life/cross-flared-green.webp",
  "level 7: +30 max hp": "icons/magic/life/cross-flared-green.webp",
  "level 6: +25 max hp": "icons/magic/life/cross-flared-green.webp",
  "altered appearance": "icons/creatures/magical/spirit-undead-ghost-blue.webp",
  "aquatic adaptation": "icons/creatures/fish/fish-bluefin-yellow-blue.webp",
  "natural weapon": "icons/creatures/abilities/fang-tooth-blood-red.webp",
  "charmed": "systems/dnd5e/icons/svg/statuses/charmed.svg",
  "carrying message": "icons/sundries/documents/envelope-sealed-red-brown.webp",
  "sympathy": "icons/magic/control/modfiy-luck-fortune-gray.webp",
  "frightened": "systems/dnd5e/icons/svg/statuses/frightened.svg",
  "suspended animation": "icons/magic/time/hourglass-brown-orange.webp",
  "banished": "icons/creatures/unholy/demon-fire-horned-clawed.webp",
  "bark-like skin": "icons/magic/nature/barrier-shield-wood-vines.webp",
  "befuddled": "icons/skills/trades/academics-investigation-puzzles.webp",
  "blessed": "icons/magic/holy/chalice-glowing-gold-water.webp",
  "ethereal": "systems/dnd5e/icons/svg/statuses/ethereal.svg",
  "blurred": "icons/magic/control/silhouette-hold-change-blue.webp",
  "indifference": "icons/magic/symbols/question-stone-yellow.webp",
  "calmed": "icons/magic/holy/yin-yang-balance-symbol.webp",
  "blocked healing": "icons/magic/life/heart-broken-red.webp",
  "blinded": "systems/dnd5e/icons/svg/statuses/blinded.svg",
  "comprehension": "icons/sundries/books/book-open-purple.webp",
  "confused": "icons/magic/symbols/question-stone-yellow.webp",
  "infected (constitution)": "systems/dnd5e/icons/svg/abilities/constitution.svg",
  "infected (intelligence)": "systems/dnd5e/icons/svg/abilities/intelligence.svg",
  "infected (wisdom)": "systems/dnd5e/icons/svg/abilities/wisdom.svg",
  "infected (strength)": "systems/dnd5e/icons/svg/abilities/strength.svg",
  "infected (dexterity)": "systems/dnd5e/icons/svg/abilities/dexterity.svg",
  "infected (charisma)": "systems/dnd5e/icons/svg/abilities/charisma.svg",
  "contingency spell": "icons/magic/time/hourglass-tilted-glowing-gold.webp",
  "protection from death": "icons/magic/death/skull-horned-worn-fire-blue.webp",
  "disguised": "icons/magic/control/silhouette-aura-energy.webp",
  "dispelling evil and good": "icons/magic/light/orb-hands-humanoid-yellow.webp",
  "blinded, deafened": "systems/dnd5e/icons/svg/statuses/blinded.svg",
  "blinded, deafened, stunned": "systems/dnd5e/icons/svg/statuses/stunned.svg",
  "death": "systems/dnd5e/icons/svg/statuses/dead.svg",
  "deafened": "systems/dnd5e/icons/svg/statuses/deafened.svg",
  "dominated": "icons/creatures/mammals/bull-horns-eyes-glowin-orange.webp",
  "trance state": "icons/magic/control/hypnosis-mesmerism-eye-tan.webp",
  "buried in rubble": "icons/environment/settlement/building-rubble.webp",
  "enhanced wisdom": "systems/dnd5e/icons/svg/abilities/wisdom.svg",
  "enhanced dexterity": "systems/dnd5e/icons/svg/abilities/dexterity.svg",
  "enhanced intelligence": "systems/dnd5e/icons/svg/abilities/intelligence.svg",
  "enhanced charisma": "systems/dnd5e/icons/svg/abilities/charisma.svg",
  "enhanced strength": "systems/dnd5e/icons/svg/abilities/strength.svg",
  "reduced": "icons/magic/control/silhouette-grow-shrink-blue.webp",
  "enlarged": "icons/magic/control/silhouette-grow-shrink-tan.webp",
  "ensnared": "icons/magic/nature/root-vine-entangled-hand.webp",
  "restrained": "systems/dnd5e/icons/svg/statuses/restrained.svg",
  "distracted": "icons/magic/symbols/question-stone-yellow.webp",
  "sickened": "systems/dnd5e/icons/svg/statuses/poisoned.svg",
  "asleep": "systems/dnd5e/icons/svg/statuses/unconscious.svg",
  "panicked": "systems/dnd5e/icons/svg/statuses/frightened.svg",
  "outlined": "icons/magic/control/silhouette-hold-change-green.webp",
  "flying steed": "icons/svg/wing.svg",
  "turning to stone": "icons/magic/defensive/armor-stone-skin.webp",
  "unable to move": "icons/magic/life/heart-broken-red.webp",
  "flight": "icons/creatures/abilities/wings-birdlike-blue.webp",
  "unrestricted movement": "icons/skills/movement/feet-bladed-boots-fire.webp",
  "under orders": "icons/skills/wounds/anatomy-organ-brain-pink-red.webp",
  "glib": "icons/magic/control/mouth-smile-deception-purple.webp",
  "invisible": "systems/dnd5e/icons/svg/statuses/invisible.svg",
  "survival guidance": "systems/dnd5e/icons/svg/activity/check.svg",
  "intimidation guidance": "systems/dnd5e/icons/svg/activity/check.svg",
  "performance guidance": "systems/dnd5e/icons/svg/activity/check.svg",
  "acrobatic guidance": "systems/dnd5e/icons/svg/activity/check.svg",
  "nature guidance": "systems/dnd5e/icons/svg/activity/check.svg",
  "deception guidance": "systems/dnd5e/icons/svg/activity/check.svg",
  "investigation guidance": "systems/dnd5e/icons/svg/activity/check.svg",
  "stealth guidance": "systems/dnd5e/icons/svg/activity/check.svg",
  "medicine guidance": "systems/dnd5e/icons/svg/activity/check.svg",
  "arcana guidance": "systems/dnd5e/icons/svg/activity/check.svg",
  "insight guidance": "systems/dnd5e/icons/svg/activity/check.svg",
  "history guidance": "systems/dnd5e/icons/svg/activity/check.svg",
  "persuasion guidance": "systems/dnd5e/icons/svg/activity/check.svg",
  "religion guidance": "systems/dnd5e/icons/svg/activity/check.svg",
  "sleight of hand guidance": "systems/dnd5e/icons/svg/activity/check.svg",
  "perception guidance": "systems/dnd5e/icons/svg/activity/check.svg",
  "athletic guidance": "systems/dnd5e/icons/svg/activity/check.svg",
  "animal handling guidance": "systems/dnd5e/icons/svg/activity/check.svg",
  "hasted": "icons/magic/time/clock-spinning-gold-pink.webp",
  "lethargy": "icons/tools/nautical/anchor-blue.webp",
  "heated metal": "icons/magic/fire/flame-burning-chain.webp",
  "feast's benefits": "icons/consumables/food/cooked-ribs-rack-glazed-bones-brown-white.webp",
  "bravery": "icons/magic/control/control-influence-crown-yellow.webp",
  "hexed intelligence": "systems/dnd5e/icons/svg/abilities/intelligence.svg",
  "hexed dexterity": "systems/dnd5e/icons/svg/abilities/dexterity.svg",
  "hexed constitution": "systems/dnd5e/icons/svg/abilities/constitution.svg",
  "hexed wisdom": "systems/dnd5e/icons/svg/abilities/wisdom.svg",
  "hexed strength": "systems/dnd5e/icons/svg/abilities/strength.svg",
  "hexed charisma": "systems/dnd5e/icons/svg/abilities/charisma.svg",
  "paralyzed": "systems/dnd5e/icons/svg/statuses/paralyzed.svg",
  "holy protection": "icons/svg/mage-shield.svg",
  "hypnotized": "icons/magic/control/hypnosis-mesmerism-eye-tan.webp",
  "hedged prison": "systems/dnd5e/icons/svg/activity/summon.svg",
  "minimus containment": "icons/svg/down.svg",
  "slumber": "systems/dnd5e/icons/svg/statuses/unconscious.svg",
  "burial": "systems/dnd5e/icons/svg/statuses/burrowing.svg",
  "chaining": "systems/dnd5e/icons/svg/statuses/restrained.svg",
  "levitating": "icons/magic/control/silhouette-hold-change-blue.webp",
  "catatonic": "icons/magic/control/hypnosis-mesmerism-eye-tan.webp",
  "trapped soul": "icons/containers/kitchenware/vase-clay-painted-brown-white.webp",
  "magic weapon +2": "icons/skills/melee/weapons-crossed-swords-black-gray.webp",
  "magic weapon +3": "icons/skills/melee/weapons-crossed-swords-pink.webp",
  "magic weapon +1": "icons/skills/melee/weapons-crossed-swords-black.webp",
  "lingering acid": "icons/magic/acid/dissolve-arm-flesh.webp",
  "mind blanked": "icons/sundries/documents/paper-plain-white.webp",
  "spiked": "icons/skills/targeting/target-strike-gray.webp",
  "duplicate a": "icons/sundries/flags/banner-pink.webp",
  "duplicate b": "icons/sundries/flags/banner-green.webp",
  "duplicate c": "icons/sundries/flags/banner-blue.webp",
  "memory modification": "systems/dnd5e/icons/svg/statuses/incapacitated.svg",
  "hidden from divination": "icons/magic/perception/mask-stone-eyes-orange.webp",
  "masked": "icons/equipment/head/mask-horned-brown.webp",
  "trapped in ice": "icons/magic/water/barrier-ice-water-cube.webp",
  "enclosed in sphere": "icons/commodities/gems/gem-amber-insect-orange.webp",
  "short dance": "icons/magic/time/clock-analog-gray.webp",
  "concealed": "icons/magic/nature/stealth-hide-beast-eyes-green.webp",
  "fears manifested": "icons/magic/death/skull-horned-white-purple.webp",
  "bound to service": "icons/magic/control/debuff-chains-shackles-movement-blue.webp",
  "no movement": "icons/svg/anchor.svg",
  "stunned": "systems/dnd5e/icons/svg/statuses/stunned.svg",
  "healed by prayer": "icons/magic/holy/prayer-hands-glowing-yellow.webp",
  "petrifying (indigo)": "icons/magic/defensive/armor-stone-skin.webp",
  "teleporting (violet)": "icons/magic/control/silhouette-grow-shrink-blue.webp",
  "restrained (indigo)": "systems/dnd5e/icons/svg/statuses/restrained.svg",
  "blinded (violet)": "systems/dnd5e/icons/svg/statuses/blinded.svg",
  "prismatic blinding": "systems/dnd5e/icons/svg/statuses/blinded.svg",
  "poison protection": "icons/equipment/head/mask-plague-leather-brown.webp",
  "resurrection sickness (day 3)": "icons/svg/stoned.svg",
  "resurrection sickness (day 2)": "icons/svg/stoned.svg",
  "resurrection sickness (day 1)": "icons/svg/stoned.svg",
  "resurrection sickness (day 4)": "icons/svg/stoned.svg",
  "bonded telepathy": "icons/skills/social/diplomacy-handshake-gray.webp",
  "enervated": "icons/skills/wounds/blood-cells-disease-green.webp",
  "brief enfeeblement": "icons/skills/melee/sword-damaged-broken-glow-red.webp",
  "reduced movement": "icons/magic/water/projectile-icecicle-glowing.webp",
  "regenerating": "icons/magic/life/cross-yellow-green.webp",
  "necrotic protection": "systems/dnd5e/icons/svg/damage/necrotic.svg",
  "radiant protection": "systems/dnd5e/icons/svg/damage/radiant.svg",
  "bludgeoning protection": "systems/dnd5e/icons/svg/damage/bludgeoning.svg",
  "piercing protection": "systems/dnd5e/icons/svg/damage/piercing.svg",
  "slashing protection": "systems/dnd5e/icons/svg/damage/slashing.svg",
  "spell taxed": "systems/dnd5e/icons/svg/break-concentration.svg",
  "seared": "icons/magic/fire/flame-burning-skull-orange.webp",
  "changed appearance": "icons/equipment/head/mask-carved-face-orange.webp",
  "sequestered": "icons/magic/control/debuff-chains-orb-movement-blue.webp",
  "imperceptible barrier": "icons/equipment/shield/heater-steel-crystal-red.webp",
  "shimmering field": "icons/magic/defensive/shield-barrier-blue.webp",
  "shillelagh (1d10)": "icons/magic/nature/root-vine-coiled-crook.webp",
  "shillelagh (1d8)": "icons/magic/nature/root-vine-coiled-crook.webp",
  "shillelagh (2d6)": "icons/magic/nature/root-vine-coiled-crook.webp",
  "shillelagh (1d12)": "icons/magic/nature/root-vine-coiled-crook.webp",
  "shining": "icons/magic/light/explosion-star-glow-silhouette.webp",
  "shocked": "icons/magic/lightning/bolt-strike-wide-white.webp",
  "silenced": "icons/magic/control/encase-creature-humanoid-hold.webp",
  "sleeping": "icons/magic/control/sleep-bubble-purple.webp",
  "slowed": "icons/magic/time/clock-stopwatch-white-blue.webp",
  "stabilized": "systems/dnd5e/icons/svg/trait-damage-vulnerabilities.svg",
  "bestial communication": "icons/creatures/mammals/dog-husky-white-blue.webp",
  "speaking with plants": "icons/magic/nature/tree-animated-squint.webp",
  "half speed": "icons/magic/movement/abstract-ribbons-red-orange.webp",
  "illuminated": "icons/sundries/lights/lantern-iron-lit-yellow.webp",
  "stinking poison": "icons/magic/acid/dissolve-vomit-green-brown.webp",
  "pursuing suggestion": "icons/tools/navigation/map-marked-red.webp",
  "incapacitated": "systems/dnd5e/icons/svg/statuses/incapacitated.svg",
  "arguing": "icons/skills/wounds/injury-face-impact-orange.webp",
  "uncontrollable laughter": "icons/magic/control/silhouette-fall-slip-prone.webp",
  "booming voice": "icons/environment/people/cleric-orange.webp",
  "universal communication": "icons/environment/settlement/pyramid.webp",
  "truesight": "icons/magic/perception/eye-slit-orange.webp",
  "ranged weapon": "icons/skills/ranged/arrow-strike-glowing-teal.webp",
  "mocked": "icons/sundries/flags/banner-flag-white.webp",
  "bonded": "icons/equipment/finger/ring-band-engraved-scrolls-silver.webp",
  "water walking": "icons/creatures/amphibians/frog-water-teal.webp",
  "frightening terrors": "systems/dnd5e/icons/svg/statuses/frightened.svg",
  "cloud form": "icons/magic/air/weather-clouds.webp",
  "wish stress": "icons/magic/symbols/star-solid-gold.webp",
  "cannot lie": "icons/skills/social/wave-halt-stop.webp"
};

const SCHOOL_MAP: Record<string, string> = {
  "transmutation": "icons/magic/control/energy-stream-link-large-teal.webp",
  "divination": "icons/magic/perception/eye-ringed-glow-angry-small-red.webp",
  "abjuration": "icons/skills/melee/strike-blade-knife-orange-blue.webp",
  "evocation": "icons/magic/light/explosion-star-large-pink.webp",
  "conjuration": "icons/magic/nature/wolf-paw-glow-large-orange.webp",
  "illusion": "icons/magic/air/fog-gas-smoke-dense-gray.webp",
  "enchantment": "icons/magic/air/air-burst-spiral-pink.webp",
  "necromancy": "icons/magic/life/heart-cross-purple-orange.webp"
};

export function getSpellIcon(name: string, school?: string): string | null {
  const lname = name.toLowerCase().trim();

  // Exact name match
  if (NAME_MAP[lname]) return BASE + '/' + NAME_MAP[lname];

  // Partial name match (e.g. "Fireball" matches "fireball of doom")
  for (const [key, path] of Object.entries(NAME_MAP)) {
    if (lname.includes(key) || key.includes(lname)) return BASE + '/' + path;
  }

  // School fallback
  if (school) {
    const ls = school.toLowerCase();
    if (SCHOOL_MAP[ls]) return BASE + '/' + SCHOOL_MAP[ls];
  }

  return null;
}
